data_name: adult
version: 2
num_data: 20000

# bandit
num_arm: 2
dim_context: 14
T: 10000

# train
algo: MALATS
model: neural
act: ReLU
layers: [100]
reduce: 2
num_iter: 100
eps: 0.01
beta_inv: 1.0
lr: 0.01

# log
project: ContextualBandit-ICML
group: Adult-MALATS