data_name: covertype
version: 3
num_data: 15000

# bandit
num_arm: 7
dim_context: 54
T: 15000

# train
algo: NeuralEpsGreedy
model: neural
act: elu
layers: [64, 64, 64, 64]
num_iter: 100
eps: 0.1
lr: 0.1

# log
project: ContextualBandit-UCI
group: Covertype-NeuralEpsGreedy