datapath: data/gaussian50-20-1-1.pt

bandit:
  num_arm: 50
  dim_context: 20
  T: 1000
  sigma: 0.01

train:
  algo: LMCTS
  num_iter: 20
  beta: 0.0001
  lr: 0.005

log:
  project: ContextualBandit
  group: LMCTS-sim-tuning