datapath: data/shuttle.trn

bandit:
  num_arm: 7
  dim_context: 9
  T: 10000

train:
  algo: LMCTS
  num_iter: 50
  beta_inv: 0.0001
  lr: 0.001

log:
  project: ContextualBandit-UCI
  group: LMCTS-test