datapath: data/gaussian50-20-1-1.pt
# bandit
num_arm: 50
dim_context: 20
index: 0
T: 5000
sigma: 1.0
func: linear

# train
algo: LMCTS
model: linear
num_data: 1
lr: 0.05
num_iter: 30
beta_inv: 0.0001

# log
project: ContextualBandit-ICML
group: Fixed-Linear-LMCTS