datapath: data/gaussian50-20-1-1.pt

bandit:
  num_arm: 50
  dim_context: 20
  T: 10000
  sigma: 1.0
  func: quad

train:
  algo: LMCTS
  model: neural
  layers: [100, 100]
  num_iter: 50
  beta_inv: 0.00001
  lr: 0.01

log:
  project: ContextualBandit-simulation
  group: LMCTS-quad