datapath: data/gaussian50-20-1-1.pt
# bandit
num_arm: 50
dim_context: 20

index: 0
num_data: 1
T: 30000
sigma: 0.0
func: logistic

# train
algo: UCBGLM
model: linear
loss: Logistic
num_iter: 100
nu: 0.1
reg: 0.0
lr: 10.0

# log
project: ContextualBandit-ICML
group: Logistic-UCBGLM